### ISSUE TITLE
设置textField第一响应

### ISSUE THREAD

**Issue by dearDragon** [cgmsuccess/CustomKeyBoard#3]
设置textField第一响应时弹出的键盘还是系统的，这个问题能怎么解决呢。demo中我设置了 [XMTextField becomeFirstResponder]。希望能快点回复我哈，谢谢。

**Comment by cgmsuccess** [comment]
生命周期导致的。 可以在业务里，先延后0.5s设置第一响应者， 解决这个问题， 后续修复这个问题
 
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.5f * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        [XMTextField  becomeFirstResponder];
    });
